// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmludkaztrztxhaulskq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtbHVka2F6dHJ6dHhoYXVsc2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDcyNjEsImV4cCI6MjA2NjE4MzI2MX0.lo-TiCNIWRCFWVWd4w42-mrHpnC7atHOhWbfD6p47mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);